local options = {
	backup = false,
	clipboard = "unnamedplus",
	cmdheight = 1,
	cursorline = true,
	expandtab = true,
	fileencoding = "utf-8",
	hlsearch = true,
	ignorecase = true,
	laststatus = 2,
	mouse = "",
	number = true,
	pumblend = 15,
	pumheight = 10,
	relativenumber = true,
	scrolloff = 10,
	shell = "fish",
	shiftwidth = 2,
	showmode = false,
	showtabline = 2,
	sidescrolloff = 10,
	signcolumn = "yes",
	smartcase = true,
	smartindent = true,
	inccommand = "split",
	splitbelow = true,
	splitright = true,
	swapfile = false,
	tabstop = 2,
	termguicolors = true,
	timeoutlen = 500,
	undofile = true,
	updatetime = 300,
	wildignore = { "__pycache__", "*.pyc" },
	wildoptions = "pum",
	wrap = false,
}

for k, v in pairs(options) do
	vim.opt[k] = v
end
