[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l"]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"
