syntax on

set nocompatible
set number relativenumber
set clipboard=unnamedplus
set hidden

set encoding=utf-8
set fileencoding=utf-8

set expandtab
set smartindent autoindent
set shiftround

set ignorecase
set smartcase
set incsearch hlsearch
set showmatch

set scrolloff=8
set sidescrolloff=8
set linebreak
set showcmd ruler
set laststatus=2
set signcolumn=yes

set wildmenu wildmode=longest:full,full
set showmode
set completeopt=menuone,noinsert,noselect

set updatetime=300
