source $HOME/.config/nvim/plugins.vim

lua require("user.autopairs")
lua require("user.bufferline")
" lua require("user.cmp")
lua require("user.coq")
lua require("user.colorscheme")
lua require("user.comment")
lua require("user.keymaps")
lua require("user.lsp")
lua require("user.lualine")
lua require("user.nvim-tree")
lua require("user.options")
lua require("user.telescope")
lua require("user.treesitter")
lua require("user.toggleterm")
