require("user.autocmd")
require("user.autopairs")
require("user.bufferline")
-- require("user.cmp")
require("user.colorscheme")
require("user.comment")
require("user.coq")
require("user.gitsigns")
require("user.illuminate")
require("user.indentline")
require("user.keymaps")
-- require("user.lsp")
require("user.lspconfig")
require("user.lspsaga")
require("user.null_ls")
require("user.lualine")
require("user.nvim-tree")
require("user.options")
require("user.plugins")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
