require("user.autopairs")
require("user.bufferline")
-- require("user.cmp")
require("user.colorscheme")
require("user.comment")
require("user.coq")
require("user.gitsigns")
require("user.keymaps")
require("user.lsp")
require("user.lualine")
require("user.nvim-tree")
require("user.options")
require("user.plugins")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
